#!/bin/sh

set -e

if [ "$1" = configure ]; then
    # create system user required to run the openvpn daemon unprivileged
    adduser --quiet --system \
            --home /var/lib/openvpn/chroot \
            --gecos "NetworkManager OpenVPN" \
            --group nm-openvpn

    # create directory used for running the openvpn daemon in a chroot
    install -o nm-openvpn -g nm-openvpn -d /var/lib/openvpn/chroot/tmp
fi

#DEBHELPER#
